name: CI

on:
  push:
    branches: [master]
    paths:
      - "**.js"
      - "**.mjs"
      - "package.json"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [master]
    paths:
      - "**.js"
      - "**.mjs"
      - "package.json"
      - ".github/workflows/ci.yml"

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node: [14.x, 12.x, 10.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn --frozen-lockfile
      - run: yarn report:json
      - name: Codecov
        uses: codecov/codecov-action@v1
        if: matrix.node == '14.x' && matrix.os == 'ubuntu-latest'
        with:
          file: ./coverage/coverage-final.json
          flags: unittests
          fail_ci_if_error: true
